spring:
  application:
    name: basexamp

  datasource:
    url: jdbc:mysql://localhost:3306/db_basket
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      enabled: true
      trigger-file: .trigger-restart
    livereload:
      enabled: true
